name: Basic Go build and test

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Build
      run: go build -v ./...

    - name : Bring up docker DB containers
      run: docker compose up -d

    - name: Run test
      run: |
        sleep 30
        go test -v ./...
