name: Run tests
on:
  - pull_request

env:
  # Needed until we can incorporate docker startup into the executor container
  DOCKER_HOST: unix:///var/run/dind.sock

jobs:
  unit-tests:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v4
      with:
        go-version-file: 'go.mod'
        check-latest: true
    - name: Run dockerd
      run: |
        dockerd -H $DOCKER_HOST --userland-proxy=false &
        sleep 5
    - name: Run DB container
      working-directory: ./test
      run: docker compose up --wait --quiet-pull
    - name: Set Gitea access token
      env:
        TOKEN: ${{ secrets.CICD_REPO_TOKEN }}
      run: |
        git config --global url."https://$TOKEN:@git.vdb.to/".insteadOf https://git.vdb.to/

    - name: Build and run tests
      run: |
        until [[ "$(docker inspect -f '{{.State.Status}}' test-ipld-eth-db)" = 'running' ]]
        do sleep 1; done &
        go build ./...
        wait $!
        go test -p 1 -v ./...
